# Generated by Django 5.1 on 2025-06-28 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=150)),
                ('lastname', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(error_messages={'unique': 'An application with that email already exists.'}, max_length=254, unique=True)),
                ('birthday', models.DateField()),
                ('education', models.TextField(blank=True)),
                ('year_of_graduation', models.DateField()),
                ('skills', models.TextField(blank=True)),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=10, max_digits=10)),
                ('languages', models.TextField(blank=True)),
                ('applicant_photo', models.ImageField(blank=True, null=True, upload_to='aplicants_photos/')),
                ('applicant_cv', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('website', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
