# Generated by Django 5.1 on 2025-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_cv',
            field=models.FileField(max_length=255, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='desired_salary',
            field=models.IntegerField(blank=True),
        ),
    ]
