# Generated by Django 5.1 on 2025-05-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerprofile',
            options={},
        ),
    ]
