# Generated by Django 5.1.2 on 2025-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0002_alter_joboffers_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='jobplace',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('on-site', 'On Site'), ('hybrid', 'Hybrid')], default='on-site', max_length=20),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='jobtype',
            field=models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship')], default='full-time', max_length=20),
        ),
    ]
